name: Schedule Comands

on:
  repository_dispatch:
    types: [build]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo "You are currently in environment: ${{github.event.client_payload.env}}"
      - name: List Files
        run: |
          pwd
          ls -a
          cd /home/runner/work
          ls -a
          mkdir bikash
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Bikash
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"