name: Schedule Comands

on:
  repository_dispatch:
    types: [build]
    steps:
      - name: Display Envelope
        run: echo ${{ github.event.client_payload.env}}
        shell: bash

jobs: 
  run-windows-command:
    runs-on: windows-latest
      - name: Directory Bash
        run: echo "Current run time is- $(date +%Y-%m-%d) at $(date +%H.%M.%S)"
        shell: bash

