name: Schedule Comands

on:
  schedule:
    - cron:  '0/5 * * * *'

jobs: 
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory Bash
        run: echo "Current run time is- $(date +%Y-%m-%d) at $(date +%h.%m.%s)"
        shell: bash

