name: Schedule Comands

on:
  repository_dispatch:
    types: [build]

jobs: 
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Display Envelope
        run: echo "This is the payload envelope value."
        shell: bash
      - name: Directory Bash
        run: echo "Current run time is- $(date +%Y-%m-%d) at $(date +%H.%M.%S)"
        shell: bash

